### ISSUE TITLE
React R'dam. Autumn edition. Call for speakers. 🗣️

### ISSUE THREAD

**Issue by zubivan** [reactrotterdam/meetup#2]
Hello everyone,

Autumn is right around the corner and as we promised we are going to try to host our meetups more regularly and that means that... CALL FOR SPEAKERS is open.

If you want to present on one of our next meetups (or know someone who wants!) or feel like doing a lightning talk, please submit a comment under this issue in the following format:

👋NAME 
✍️TALK TITLE
📖SHORT ABSTRACT

Otherwise, feel free to reach out via the usual channels that you can find https://github.com/reactrotterdam/meetup#contributing.

**Comment by pvinis** [comment]
I don't know when this is for, but if it's around october or so, I might be into doing it.

👋 Pavlos Vinieratos
✍️ Using rxjs with React Native
📖 You can use rxjs to replace redux/mobx/whatever else. Let rxjs manage your local state and anything else. This allows the UI and the logic(rxjs) to be tested separately. This talk will be showing off some simple components and some screen components that we can control with rxjs. Mostly a demo talk.

**Comment by zubivan** [comment]
@pvinis hi there! We are not yet sure whether we want to have it in September or October, but if you're up for I'll can schedule the next one in October.
All depends on whether we can find speakers.

Since your talk is about React Native, we were thinking (it was actually @JefHellemans's idea) to maybe have an evening purely focused on React Native.

**Comment by JefHellemans** [comment]
This sounds like a great subject, thanks for submitting @pvinis!

**Comment by gklijs** [comment]
I was contacted by @jhuiting to maybe do a talk similar to the one I will be giving at [GraphQL Summit](https://summit.graphql.com/).
👋Gerard Klijs
✍️Expose your Kafka with GraphQL
📖I will demo an application which uses GraphQL to let the frontend interact with the backend. The backend part will produce to and consume from Kafka, using subscriptions to pass events to the frontend as soon as they are read. The frontend is build with re-frame, which is a Clojurescript framework based on React.

**Comment by zubivan** [comment]
@gklijs Hi Gerard, sounds like an interesting topic!

**Comment by zubivan** [comment]
@pvinis @gklijs are you gents both available at the beginning (first week) of October? If so, I'd schedule the next meetup.

**Comment by pvinis** [comment]
Unfortunately, I fly away on 4th Oct and come back 22nd, so I might need to skip this one..

**Comment by gklijs** [comment]
First week of October would be fine for me, rather not on the 3rd however.

**Comment by pvinis** [comment]
Turns out I will have some time in sept too, between the 9th and the 25th. Otherwise yea maybe 1-3 oct?

**Comment by zubivan** [comment]
@pvinis @gklijs let me quickly check if have the space available for 1-3 Oct.

**Comment by zubivan** [comment]
Alright! We got space and the draft meetup event => https://www.meetup.com/React-Rotterdam/events/264307774/ !

As usual I will need short bios from you folks and twitter handles (if you have one). @pvinis @gklijs

**Comment by zubivan** [comment]
@gklijs @pvinis hm, will 3rd work for you or 2nd is a better option? (Somehow missed your comment 🤦‍♂ )

**Comment by pvinis** [comment]
2nd is nicer for me because its earlier, but both work.

**Comment by gklijs** [comment]
2nd is better for me as well (internal meetup the 3rd)

**Comment by zubivan** [comment]
@gklijs @pvinis alrighty. Moving it to the 2nd of October. I'll update the event and put the information I already have in there.

**Comment by zubivan** [comment]
@pvinis @gklijs aaaand it's announced and added to the website.

Please send me your BIOs, so I can fill-in `About our speakers` section on the meetup page.

And see you in October 👍
