### ISSUE TITLE
React R'dam. Late Autumn/early winter edition. Call for speakers.

### ISSUE THREAD

**Issue by zubivan** [reactrotterdam/meetup#4]
Hello everyone,

Autumn meetup was just scheduled, so it's time to look forward for the next edition! Since we promised we are going to try to host our meetups more regularly and that means that... CALL FOR SPEAKERS is open.

If you want to present on one of our next meetups (or know someone who wants!) or feel like doing a lightning talk, please submit a comment under this issue in the following format:

👋NAME
✍️TALK TITLE
📖SHORT ABSTRACT

Otherwise, feel free to reach out via the usual channels that you can find https://github.com/reactrotterdam/meetup#contributing.

**Comment by ghengeveld** [comment]
👋 Gert Hengeveld
✍️ Going Component-Driven
📖 Building apps is all about components. Modern frameworks have established patterns for building UIs from well specified components. Are you applying these patterns properly, and is your workflow optimized for it?

Component-Driven Development (CDD) is a development methodology that centralizes components in the development process. It means building UIs from the bottom up, from components to screens to pages. Storybook is the leading tool that enables the CDD workflow. Complementary to that you'll soon be able to integrate this into your team with Chroma, a free collaboration tool for Storybook. Let's take a look at what that means in practice.

**Comment by ghengeveld** [comment]
👋 Gert Hengeveld
✍️ Building a Chrome DevTools extension for React Async
📖 Part of every successful open source project is a great developer experience. I've always felt the Network DevTools in Chrome to be lacking for single-page apps with a lot of XHR going on. Throttling your network speed to test a loading indicator kind of works, but leaves a lot to be desired. What if we could build our own alternative that enables throttling XHR on a case-by-case basis, or even allows you to replay an individual request? That would provide a much better developer experience. Here's how it works.

**Comment by wspringer** [comment]
👋Wilfred Springer
✍️Get Reasonable with React
📖ReasonML is the much-rumored yet little-known programming language that shares its ancestry with React itself. Like TypeScript, it is a statically typed language for the JavaScript eco-system, but unlike TypeScript it doesn't import all of its bad parts. If you ever wondered what is powering Facebook's Messenger: it's ReasonML. And not just for its interesting language features, but also because it's able to target native binaries *directly*. So, where React Native is relying on JavaScript to be the driver of all of its native components, when using ReasonML you *could* yank out JavaScript and replace it with the platform optimized code generated by ReasonML. 

In this talk, I will give a brief overview of the language and show you how to use it to build a React application.

**Comment by wilcoschoneveld** [comment]
👋Wilco Schoneveld
✍️Building user interfaces with finite state machines

📖How do state machines work and how can they contribute to a robust and scalable user interface? How does it compare to other state management approaches? In this talk I will dive into the world of statecharts and explore its potential and limits for use in frontend applications. I will give concrete examples with React & XState and show how to split up the application logic into multiple machines with the Actor model.

**Comment by zubivan** [comment]
@ghengeveld @wspringer @wilcoschoneveld so! I think we have a lineup! We're usually try to do at max two talks per evening and maybe one lightning talk? What are you folks after?

**Comment by ghengeveld** [comment]
Usually I prefer regular 30m talks, because I tend to spend a lot of time preparing regardless of the length of the talk. However if lightning is meant for a more casual presentation style with less prep, I can do that too.

FYI I'm not available to present from December probably until March, as we're expecting a baby (a girl this time).

**Comment by wspringer** [comment]
How much time would you normally reserve for a "regular" talk? Explaining ReasonML is not something I can imagine doing in five minutes, so I don't think my talk would fit the lighting talk description. 😬

**Comment by wilcoschoneveld** [comment]
I am looking to get a time slot of 45 minutes

**Comment by zubivan** [comment]
@ghengeveld congratulations!

@wilcoschoneveld @wspringer we are doing it this way usually:

*Lightning talk*: 10-15 minutes
*Regular talk*: 30-45 minutes

**Comment by wspringer** [comment]
I would go for regular then. :-)

**Comment by zubivan** [comment]
@wspringer @wilcoschoneveld @ghengeveld 
Shall we aim for the last week of November? Let me know what's your availability folks.

**Comment by ghengeveld** [comment]
Tue/wed/fri is fine that week.

**Comment by wilcoschoneveld** [comment]
Wednesday 27 nov works best for me! otherwise monday or tuesday

**Comment by zubivan** [comment]
@ghengeveld @wilcoschoneveld alrighty, shall we aim for 27th of November? I'll create a draft meetup.

**Comment by wilcoschoneveld** [comment]
Cool!!

**Comment by ghengeveld** [comment]
Sounds good.

**Comment by ghengeveld** [comment]
Turns out I can't make the 27th after all. Tuesday is still okay with me, and was okay with @wilcoschoneveld as well. Hope it works out.

**Comment by wspringer** [comment]
I think Tuesday would be fine for me. Checking conference schedules now,
just to be sure.

**Comment by wilcoschoneveld** [comment]
@zubivan are you looking to put three talks in one session? Otherwise I'm ok to present in a future session (e.g. early 2020)

**Comment by zubivan** [comment]
I think 3 session is probably a bit too much.

@ghengeveld @wspringer shall we do two on Tuesday the 26th of November?

@wilcoschoneveld I think that would be even better!

**Comment by ghengeveld** [comment]
Yes thats fine.

**Comment by ghengeveld** [comment]
I assume you mean November.

**Comment by zubivan** [comment]
Oh, yes. Changed it, thanks!

**Comment by wilcoschoneveld** [comment]
👍

**Comment by zubivan** [comment]
@wspringer what about you? Can you make it on 26th?

**Comment by wspringer** [comment]
Yes!

**Comment by zubivan** [comment]
And boom!

https://www.meetup.com/React-Rotterdam/events/265895503

See you folks in November!

@ghengeveld @wspringer I'll need your bios (just couple of sentences) and twitter handles.
